__version__ = "1.0.2"
__author__ = "Daniel Andersson"
__maintainer__ = "Daniel Andersson"
__email__ = "daniel.4ndersson@gmail.com"
__status__ = "Production"
__url__ = "https://github.com/Penlect/line-protocol-parser"
__license__ = "MIT"